version: "3.7"
services:
  web:
    image: vitcmun/munverse:latest
    container_name: munverse_container
    depends_on:
      - mongo
    restart: always
    env_file: .env
    environment:
      NODE_ENV: $NODE_ENV
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_DB: $MONGO_DB
    command: ["scripts/wait-for-it.sh", "mongo:27017", "--", "scripts/startup.sh"]
    ports:
      - "80:8080"
  mongo:
    image: mongo
    container_name: munverse_mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./db/seed.js:/docker-entrypoint-initdb.d/seed.js
      - dbdata:/data/db
volumes:
  dbdata: