# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo:3.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          name: tests
          command: npm test
          environment:
            NODE_ENV: test
            MONGO_USERNAME: test
            MONGO_PASSWORD: test
            MONGO_HOSTNAME: localhost
            MONGO_PORT: 27017
            MONGO_DB: test
  deploy:
    machine: true
    steps:
      - checkout

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: export TAG=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json) >> $BASH_ENV

      - run:
          name: create docker image
          command: docker build -f build.Dockerfile -t vitcmun/munverse:$TAG.$CIRCLE_BUILD_NUM .

      - run:
          name: push to dockerhub
          command: docker push vitcmun/munverse:$TAG.$CIRCLE_BUILD_NUM

# test -> deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

